name: Linting Tests (ESLint)

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: ESLint run
        uses: sibiraj-s/action-eslint@v2
        with: 
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true