name: Linting Tests (ESLint)

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install modules
      run: npm

    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx