name: Feature Tests (Cypress)

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start

      - name: Run Jest
        run: npm test

      - name: Run ESLint
        run: npm run lint