name: All Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: npm install
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Run Jest
        run: npm test

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm start
